### ISSUE TITLE
5wd2讨论纪要：有一种故事叫做“家族故事”

### ISSUE THREAD

**Issue by xudoujiang** [BridgeOfStories/FamiliyStories#2]
在这里简单汇报一下我（许豆浆）和@mumu 线下快速会面的讨论哈。
### 1、『故事』很宽泛，得找一个切入口。

公元2016年4月12日，即写作课计时5wd3，@xudoujiang与@mumu 碰了个面，在场还有一位5岁孩子的妈妈@hui（mumu的朋友）——将她当目标用户来访问。
### 2、第一个方向：个性化推送

说到”孩子、故事“，自然就想到”给孩子讲故事“。拿着绘本讲故事、用手机播音频给孩子听故事、iPad电视上的动画片？也是一种故事。现在，免费的故事资源非常丰富。作为一个经常和孩子读绘本、口头交流故事的妈妈，hui的体会是：针对孩子现阶段的一些成长需要（比如，不爱刷牙啦、有早恋对象啦，呃）而个性化配置、推送的故事，就比较稀缺了。`个性化的精细程度，可以再思考下去。`

打个比方，有点像”列书单“。比如上认知写作课，阳老会给开列书单——学习这门课程的学员、对此学科有兴趣钻研的人，会得到这份书单；

进一步，这个书单里有难有易，从哪读起好呢？这是一个可以问老师、也可以通过（算法？）个性化配置的问题。

再进一步，将每本书切分成段，在适合的场景里推送（比如睡前10分钟、开车通勤的路上30分钟）来推送，也是个性化配置。`抛砖引玉，欢迎延伸`

总结起来就是：
**千言万语，不如懂你。**

OK，这是一种思路。
### 3、第二个方向：孩子从家庭故事中汲取到”归属“的力量

这一点是我针对”故事“的类型提出来的。我们每天跟孩子讲/交流的故事何其多：西游记、童话、科幻……但是，那些都是”别人家“的故事，为什么不能说一说，我们自己的故事呢？`说出你的故事（鲁豫脸）`

我个人有参与一些教育项目，在跟孩子探究”自我“时，离不开孩子成长的家庭环境及成员。国外的课程常常会见到”familiy tree“之类的作业或活动，就是让孩子了解自己的家庭成员以及他们的故事。研究表明：

> 孩子们对于家族历史知道得越多，他们就越有控制自己人生的意识，自尊心就越强，也就越相信自己的家庭做得更成功。_“你知道（你爸你妈你爷爷奶奶大姑二舅的故事）吗”测试表_从而成为儿童情绪健康与幸福的唯一最佳预测系统。
> `当然括号里的字是鄙人加上去的嘿嘿`

推荐阅读[这篇文章](http://learning.sohu.com/20150226/n409176138.shtml)，大概会get到我的意图。

so，我想让爸爸妈妈来讲讲，自己的故事。
作为大人的我们，作为子女的我们，对自己爹娘的故事又了解多少呢？啊……
### 4、待解决：更多的IDEA？以及找到一个“最小支点”

如果分别从以上两个IDEA出发，大家能想到什么样的“最小支点”呢？
因为故事始终是个比较抽象的东西，我们能浮现的就是文本啦、写的讲的画的……但是好像都是比较有难度的活动呢。不信，让你写一个故事那个作业，不是愁死宝宝了吗？

我理解中的最小支点，是一个比较“具象”的东西。今天看到一篇文章，我觉得这个[“友谊凳”](http://www.zhentiyuan.com/news/14812_9179.html)，就很接近我对最小支点的理解诶～`不知道是不是一种谬解啊请指教`

**Comment by mumu1314** [comment]
“编一个故事”和“和讲述自己的故事”还是有区别的，相对第二个难度小很多。友谊凳给我很大启发，把故事和一个具体的物品联系起来是非常好的做法，孩子会对大人的东西很感兴趣的，可以每次从一个家里的东西开始，讲这个东西的故事，只要有一个切入点，开了口，再继续延伸就容易很多了。

**Comment by Linkding** [comment]
我表示也支持，第二个方向：
- 孩子了解家长的故事，成长历史，寻找自己的时间源头
- 增强家庭认同感，归属感；
- 获得家族良好模因；

关于最小支点思考：
我脑袋里经常有妈给我讲她成长的年代，干农活的场景，遇到了农田里可怕的生物，走夜路去上学，和外公学厨艺，各种各样。每个父母都会无意识跟孩子讲自己的过去的，而我发现，我记得很多父母讲的事情，都是有关他们“生存优势效应的”。

那么，我们是不是可以利用“生存效应”来指定一些最小故事范围呢？

**Comment by junjielizero** [comment]
嗯哼！看了大家的解答，都在找切入点，但答案偏解决方案，好的解决方案前提是解决用户痛点（就是切入点），切入点同时决定了市场发展。

结合上面提到的点，我尝试按「需求生成」→ 「需求筛选」→ 「解决方案生成与验证」→ 「市场发展」来分析，便于视频作业落地，具体如下：

## 需求生成

通常划分流程（用户体验地图）比较容易找到需求，具体如下：
- 讲故事前 → 讲故事中 → 讲故事后

### 讲故事前：
- 父母不知找什么故事，讲给子女
- 父母难以找到合适故事（花较长时间）
- ……

### 讲故事中：
- 故事载体不好（没图、没声音），孩子没感觉
- 讲故事的环境不好，双方难以沉浸
- 父母很难找时间给孩子讲故事
- ……

### 讲故事后：
- 父母讲故事后，想和别人分享，看一下别的父母怎么讲给孩子听，分享一下孩子听完的感受
- 父母很看重小孩听完故事感受，期望他们学到东西，如果他们不能掌握，我会。。。
- ……

### 做法
- 结合头脑风暴、日常观察、用户访谈（这一点我可以帮忙，毕竟是工作），issue 提到的东西，切入进去
- 量化痛点（需求程度与需求频次），以「故事载体不好（没图、没声音），孩子没感觉」示范：
  - 需求程度：孩子抱怨图画太糟糕，没兴趣听，家长没动力接着讲，
  - 需求频次：一周两三天给孩子讲 10 - 15 min 故事
- 细化痛点（场景化/叙事描述，5 W + 1 H）：
  - 晚上家中，准备和孩子讲 XXX 故事，这个故事是我从 XXX 方式知道的，讲得过程中遇到 XXX 问题，孩子听完后觉得 XXX，听完孩子反馈后我想 XXX

### 关键（研究历史）
- 大家所有想法，在国内外是否有人做过，成效如何？我们提的点之前是不是有人掉坑呢？
- 现在国内讲故事做得好的 APP/网站/微信公众号有哪些？
  - 为什么做得好？（切入痛点与解决方案怎样）
  - 它的规模发展能否借鉴？
  - 为什么我们提的点，他们没有做？真的是没发现吗？
  - 我们的想法，现有哪些出色产品模式上差不多？（比如做个性化推荐，做的好 APP 是怎么发展的？能否参考？）

## 需求筛选

### 原则
- 用户行为高于期望与想法
- 高频行为优先
- 寻找能延续三个大版本的核心支点

### 用户行为高于期望与想法
- 用户有想法，如果未尝试过，纯粹是单想，判断是伪需求，不建议切入
- 用户有想法，尝试过，还过得去，不用切入
- 用户有想法，尝试过但十分不好，我们的解决方案（issue 上面提到）就取代他们尝试过的做法

### 高频行为优先
- 根据「需求探索」环节的量化痛点，优先考虑用户尝试过的高频行为
- 高频形成黏性，用户逐步信任和沉浸，新需求容易诞生，二次传播容易

### 寻找能支撑至少三个大版本的核心需求（未完成）
- 核心需求相当于树，之后版本新的核心需求都是从这里自然发展（如果第一个版本就实现了个性化推荐，那之后三个版本都做什么）

## 解决方案 —— 生成与验证（未完成）
- 矛盾分解，最低成本解决问题
- 阶段性实现（如果「个性化推荐」是第三版本实现，那么之前两代核心是什么，想想出现第一个销售暴增的 iPod、iPhone 是第几代，那一代的核心功能是什么，之前几代为销售暴增做了什么工作，有什么连续性）

## 市场发展（未完成）
- 与当初制定的核心需求有关，怎么发展可借用模式启发

### 种子用户

### 用户推广

### 利润模式（20 - 30 个）

## 视频演示
- 视频演示相当于写一篇文章，可以将大作业文章分解成「用户需求」、「解决方案」、「市场发展」最小内容，变成三张大卡片，每张大卡片分成五张以下小卡片
- 卡片内容来源于上面分析，如「用户需求」环节，由「需求生成」量化与细化痛点提供
- 视频文字与时间限制较大，卡片内容必须核心，能删就删，写作班哪些原理与技巧能用上，比如「可供性」效果 —— 一个产品具有多种功能（铅笔可以写字，笔芯用来润滑门锁），修辞的「默说」
- 同样，每张卡片想给人或读者效果，卡片之间怎么衔接好，有哪些原理与技巧可以用上

**Comment by serena333** [comment]
### 哈哈，路过也来说两句。第二个方向很好诶！

小时候跟家里的长辈来往比较少，后来大了慢慢听爸妈说了他们的故事，发现自己居然有一个非常风流倜傥的二姥爷，在世的长辈每个人也都有自己的经历。你会觉得那些干瘪的称呼在故事里变得鲜活起来，冥冥之中也能感觉到超越时空的血脉联系。

具体到产品的形式。既然是家族故事，肯定是和家谱有一定联系的。既然是讲故事，肯定是要降低家长讲故事的难度，从产品上给予支持。同时还可以看到或者听到别人的故事，可以相互借鉴交流。

那么是要给什么样的家长什么样的支持呢？没有给孩子讲故事意愿的暂时不谈，那么想讲故事的家长，讲什么？怎么讲？怎么讲得更好？

一个好的讲故事的状态，我想和我们学习写作是类似的，**（简单反应时＋）自主心智＋技巧的内化**。所以可以采用这样的方式：
- 整体以图片或卡片的形式呈现；
- 提供很多人物或者物品的卡片，随机抽取卡片，让家长顺着卡片的内容来讲故事；
- 依据“空间法则”，故乡是非常能引起人们联想和情绪的。所以可以设置一些场景，或者固定一个家乡的场景（由家长事先设定）（以图画的形式呈现，甚至只是文字，比如“汉江”两个字我就能讲出很多故事来），作为进一步的引导，或者是故事的存放地。
- 开始讲故事之前，可以有一些技巧的提示，比方说把“最小故事”“大脑喜欢惊奇”这样的原则改编一下教给父母，让他们把故事讲得更生动。
- 在4之前也可以和孩子有这样的互动，比方抽到了“外婆”，可以让孩子讲一下对外婆的印象，可能孩子会问“外婆为什么不爱讲话？”家长就可以顺着这一点去讲一个反转的故事之类的。

总体的策略就是，随机主题＋场景代入＋故事技巧＋和孩子的互动，让家长更容易进入自主心智，讲出精彩的故事。这里还缺少一个讲完之后的反馈，没有形成闭环。可以把app的入口设计成一张牌，一面是家长版，一面是孩子版，家长积累了一些故事之后，也可以让孩子试试来讲他眼中的家族故事。也算一种互动和反馈了～
